import type { BlogPost, Category, Order, Product, Review, User } from "@/lib/types";

export const categories: Category[] = [
  {
    id: "cat-laptop",
    name: "Laptop",
    slug: "laptop",
    description: "Laptop gaming, văn phòng và ultrabook cho mọi nhu cầu.",
    icon: "Laptop",
    isActive: true,
    sortOrder: 1,
    createdAt: "2026-01-01",
    updatedAt: "2026-01-01",
  },
  {
    id: "cat-pc",
    name: "PC",
    slug: "pc",
    description: "Dàn PC gaming, đồ họa và workstation lắp sẵn.",
    icon: "MonitorSmartphone",
    isActive: true,
    sortOrder: 2,
    createdAt: "2026-01-01",
    updatedAt: "2026-01-01",
  },
  {
    id: "cat-phone",
    name: "Điện thoại",
    slug: "dien-thoai",
    description: "Smartphone cao cấp, tầm trung và gaming phone.",
    icon: "Smartphone",
    isActive: true,
    sortOrder: 3,
    createdAt: "2026-01-01",
    updatedAt: "2026-01-01",
  },
  {
    id: "cat-monitor",
    name: "Màn hình",
    slug: "man-hinh",
    description: "Màn hình gaming, thiết kế và làm việc chuyên nghiệp.",
    icon: "Monitor",
    isActive: true,
    sortOrder: 4,
    createdAt: "2026-01-01",
    updatedAt: "2026-01-01",
  },
  {
    id: "cat-accessory",
    name: "Phụ kiện",
    slug: "phu-kien",
    description: "Chuột, bàn phím, tai nghe, dock và phụ kiện tiện ích.",
    icon: "Headphones",
    isActive: true,
    sortOrder: 5,
    createdAt: "2026-01-01",
    updatedAt: "2026-01-01",
  },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "ASUS ROG Zephyrus G14",
    slug: "asus-rog-zephyrus-g14",
    categoryId: "cat-laptop",
    brand: "ASUS",
    price: 42990000,
    originalPrice: 45990000,
    rating: 4.8,
    reviewCount: 128,
    stock: 12,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Laptop gaming 14 inch cao cấp với thiết kế gọn nhẹ và màn OLED.",
    description:
      "ROG Zephyrus G14 phù hợp game thủ và người làm nội dung cần hiệu năng cao trong thân máy nhỏ gọn. Máy nổi bật với màn hình OLED sắc nét, tản nhiệt tối ưu và thiết kế cơ động để sử dụng linh hoạt ở cả văn phòng lẫn khi di chuyển.",
    specs: {
      CPU: "AMD Ryzen 9",
      GPU: "NVIDIA GeForce RTX 4060",
      RAM: "32GB LPDDR5X",
      SSD: "1TB NVMe",
      Display: "14 inch OLED 3K 120Hz",
      Weight: "1.5kg",
    },
    featured: true,
    onSale: true,
    isNew: true,
    tags: ["gaming", "oled", "creator"],
  },
  {
    id: "p2",
    name: "Dell XPS 13 Plus",
    slug: "dell-xps-13-plus",
    categoryId: "cat-laptop",
    brand: "Dell",
    price: 36990000,
    rating: 4.7,
    reviewCount: 86,
    stock: 7,
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Ultrabook cao cấp cho doanh nhân và người dùng văn phòng.",
    description:
      "Thiết kế tối giản, màn hình 13 inch viền mỏng, hiệu năng ổn định cho công việc, học tập và di chuyển hằng ngày.",
    specs: {
      CPU: "Intel Core Ultra 7",
      RAM: "16GB LPDDR5",
      SSD: "512GB NVMe",
      Display: "13.4 inch OLED",
      Weight: "1.24kg",
    },
    featured: true,
    tags: ["office", "ultrabook"],
  },
  {
    id: "p3",
    name: "PC Gaming RTX 4080 Super",
    slug: "pc-gaming-rtx-4080-super",
    categoryId: "cat-pc",
    brand: "GearHub Build",
    price: 55990000,
    originalPrice: 58990000,
    rating: 4.9,
    reviewCount: 51,
    stock: 4,
    image: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "PC gaming hiệu năng cao cho chơi game 2K, stream và dựng video.",
    description:
      "Bộ PC được tối ưu cho nhu cầu chơi game AAA, stream và xử lý đồ họa nặng với khả năng nâng cấp tốt. Cấu hình cân bằng giữa sức mạnh GPU, tản nhiệt và nguồn điện để vận hành ổn định trong thời gian dài.",
    specs: {
      CPU: "Intel Core i7-14700KF",
      GPU: "NVIDIA GeForce RTX 4080 SUPER 16GB",
      RAM: "32GB DDR5",
      SSD: "2TB NVMe",
      PSU: "850W 80 Plus Gold",
    },
    featured: true,
    onSale: true,
    tags: ["desktop", "streaming", "rgb"],
  },
  {
    id: "p4",
    name: "iPhone 16 Pro Max",
    slug: "iphone-16-pro-max",
    categoryId: "cat-phone",
    brand: "Apple",
    price: 33990000,
    rating: 4.8,
    reviewCount: 244,
    stock: 20,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Flagship cao cấp cho người dùng cần camera mạnh và hệ sinh thái Apple.",
    description:
      "iPhone 16 Pro Max phù hợp người dùng cần một mẫu điện thoại cao cấp có hiệu năng mạnh, màn hình lớn và hệ thống camera linh hoạt cho quay chụp hằng ngày. Máy cũng là lựa chọn phù hợp khi cần đồng bộ tốt với MacBook, iPad và các thiết bị Apple khác.",
    specs: {
      Chip: "A18 Pro",
      Display: "6.9 inch OLED 120Hz",
      Camera: "48MP Fusion + 48MP Ultra Wide + 12MP Telephoto",
      Storage: "256GB",
      Battery: "Lên đến 33 giờ phát video",
    },
    featured: true,
    isNew: true,
    tags: ["flagship", "camera"],
  },
  {
    id: "p5",
    name: "Samsung Galaxy S25 Ultra",
    slug: "samsung-galaxy-s25-ultra",
    categoryId: "cat-phone",
    brand: "Samsung",
    price: 30990000,
    originalPrice: 32990000,
    rating: 4.7,
    reviewCount: 167,
    stock: 15,
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Smartphone Android cao cấp với bút S Pen và camera zoom.",
    description:
      "Galaxy S25 Ultra phù hợp người dùng cần điện thoại màn hình lớn, bút S Pen và hệ thống camera đa tiêu cự cho cả công việc lẫn giải trí. Máy mang lại hiệu năng mạnh, pin bền và trải nghiệm Android cao cấp ở nhóm flagship.",
    specs: {
      Chip: "Snapdragon 8 Elite for Galaxy",
      Display: "6.9 inch Dynamic AMOLED 2X 120Hz",
      Camera: "200MP + 50MP Ultra Wide + 50MP Tele + 10MP Tele",
      Storage: "512GB",
      Battery: "5000mAh",
    },
    onSale: true,
    tags: ["android", "s-pen", "camera"],
  },
  {
    id: "p6",
    name: "LG UltraGear 27GS95QE",
    slug: "lg-ultragear-27gs95qe",
    categoryId: "cat-monitor",
    brand: "LG",
    price: 18990000,
    rating: 4.8,
    reviewCount: 59,
    stock: 9,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Màn hình OLED 27 inch 240Hz cho game thủ eSports.",
    description:
      "Độ tương phản cao, tốc độ phản hồi nhanh và màu sắc đẹp, thích hợp chơi game tốc độ cao lẫn chỉnh ảnh.",
    specs: {
      Resolution: "2560x1440",
      Panel: "OLED",
      RefreshRate: "240Hz",
      ResponseTime: "0.03ms",
      Ports: "HDMI 2.1, DisplayPort",
    },
    featured: true,
    tags: ["monitor", "oled", "esports"],
  },
  {
    id: "p7",
    name: "Logitech G Pro X Superlight 2",
    slug: "logitech-g-pro-x-superlight-2",
    categoryId: "cat-accessory",
    brand: "Logitech",
    price: 3290000,
    originalPrice: 3790000,
    rating: 4.9,
    reviewCount: 302,
    stock: 31,
    image: "https://images.unsplash.com/photo-1613141411244-0e4ac259d217?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1613141411244-0e4ac259d217?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541140532154-b024d705b90a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Chuột gaming siêu nhẹ dành cho thi đấu.",
    description:
      "Thiết kế gọn nhẹ, cảm biến chính xác và pin bền, phù hợp người chơi FPS và eSports chuyên nghiệp.",
    specs: {
      Weight: "60g",
      Sensor: "HERO 2",
      DPI: "32.000 DPI",
      Connection: "Lightspeed Wireless",
      Battery: "95 giờ",
    },
    onSale: true,
    tags: ["mouse", "gaming", "wireless"],
  },
  {
    id: "p8",
    name: "Keychron Q1 Max",
    slug: "keychron-q1-max",
    categoryId: "cat-accessory",
    brand: "Keychron",
    price: 4890000,
    rating: 4.7,
    reviewCount: 75,
    stock: 14,
    image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541140532154-b024d705b90a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Bàn phím cơ custom không dây cho dân code và game thủ.",
    description:
      "Khung nhôm chắc chắn, hỗ trợ hot-swap và kết nối đa thiết bị. Trải nghiệm gõ cao cấp phù hợp cho công việc dài giờ.",
    specs: {
      Layout: "75%",
      Switch: "Hot-swappable",
      Connection: "2.4GHz / Bluetooth / USB-C",
      Battery: "4.000mAh",
      Material: "Full aluminum",
    },
    tags: ["keyboard", "mechanical", "custom"],
  },
  {
    id: "p9",
    name: 'MacBook Air 15" M4',
    slug: "macbook-air-15-m4",
    categoryId: "cat-laptop",
    brand: "Apple",
    price: 32990000,
    originalPrice: 34990000,
    rating: 4.9,
    reviewCount: 118,
    stock: 16,
    image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "MacBook mỏng nhẹ cho sinh viên và dân văn phòng cao cấp.",
    description:
      "Dòng MacBook Air màn lớn, pin lâu và hiệu năng ổn định cho học tập, làm việc và sáng tạo nội dung cơ bản.",
    specs: {
      Chip: "Apple M4",
      RAM: "16GB Unified Memory",
      SSD: "512GB",
      Display: "15 inch Liquid Retina",
      Battery: "Lên đến 18 giờ",
    },
    featured: true,
    onSale: true,
    tags: ["macbook", "office", "student"],
  },
  {
    id: "p10",
    name: "Lenovo Legion Pro 7",
    slug: "lenovo-legion-pro-7",
    categoryId: "cat-laptop",
    brand: "Lenovo",
    price: 47990000,
    originalPrice: 51990000,
    rating: 4.8,
    reviewCount: 64,
    stock: 8,
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1504707748692-419802cf939d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Laptop gaming cao cấp cho AAA và streaming.",
    description:
      "Hiệu năng mạnh, màn hình tần số quét cao và hệ thống tản nhiệt lớn, phù hợp người dùng cần sức mạnh tối đa.",
    specs: {
      CPU: "Intel Core Ultra 9",
      GPU: "RTX 5080",
      RAM: "32GB DDR5",
      SSD: "1TB NVMe",
      Display: "16 inch 240Hz",
    },
    featured: true,
    tags: ["gaming", "streaming", "high-end"],
  },
  {
    id: "p11",
    name: "Xiaomi 15 Ultra",
    slug: "xiaomi-15-ultra",
    categoryId: "cat-phone",
    brand: "Xiaomi",
    price: 26990000,
    originalPrice: 28990000,
    rating: 4.6,
    reviewCount: 93,
    stock: 19,
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Flagship Android tập trung camera và sạc nhanh.",
    description:
      "Máy phù hợp người thích chụp ảnh, màn hình sáng đẹp và hiệu năng mạnh trong tầm flagship.",
    specs: {
      Chip: "Snapdragon 8 Elite",
      Display: "6.73 inch AMOLED",
      Camera: '50MP Leica',
      Storage: "512GB",
      Battery: "5.300mAh",
    },
    onSale: true,
    tags: ["flagship", "camera", "android"],
  },
  {
    id: "p12",
    name: "AOC Q27G4 Gaming",
    slug: "aoc-q27g4-gaming",
    categoryId: "cat-monitor",
    brand: "AOC",
    price: 6290000,
    originalPrice: 6990000,
    rating: 4.7,
    reviewCount: 140,
    stock: 22,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Màn hình 27 inch 2K 180Hz cho game thủ tầm trung.",
    description:
      "Lựa chọn tốt cho game thủ cần cân bằng giữa màu sắc, tần số quét và chi phí đầu tư.",
    specs: {
      Resolution: "2560x1440",
      Panel: "Fast IPS",
      RefreshRate: "180Hz",
      ResponseTime: "1ms",
      Size: "27 inch",
    },
    featured: true,
    onSale: true,
    tags: ["monitor", "2k", "gaming"],
  },
  {
    id: "p13",
    name: "Sony WH-1000XM5",
    slug: "sony-wh-1000xm5",
    categoryId: "cat-accessory",
    brand: "Sony",
    price: 8990000,
    originalPrice: 9990000,
    rating: 4.8,
    reviewCount: 88,
    stock: 13,
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Tai nghe chống ồn cao cấp cho làm việc và giải trí.",
    description:
      "WH-1000XM5 phù hợp người dùng cần tai nghe chống ồn cao cấp để làm việc, di chuyển và nghe nhạc hằng ngày. Thiết kế đeo thoải mái, khả năng chống ồn hiệu quả và chất âm dễ nghe giúp sản phẩm phù hợp cả môi trường văn phòng lẫn những chuyến đi dài.",
    specs: {
      Type: "Over-ear",
      ANC: "Adaptive Noise Cancelling",
      Battery: "Tối đa 30 giờ",
      Connection: "Bluetooth 5.2",
      Weight: "250g",
    },
    onSale: true,
    tags: ["audio", "anc", "wireless"],
  },
  {
    id: "p14",
    name: "PC Creator Studio RTX",
    slug: "pc-creator-studio-rtx",
    categoryId: "cat-pc",
    brand: "GearHub Build",
    price: 42990000,
    rating: 4.8,
    reviewCount: 44,
    stock: 6,
    image: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "PC cho thiết kế, dựng phim và làm việc đa nhiệm.",
    description:
      "Bộ PC này hướng tới editor, designer và người làm 3D cần hiệu năng đa nhân tốt, nhiều RAM và GPU mạnh để xử lý dự án nặng. Cấu hình được cân bằng theo nhu cầu dựng video, thiết kế và làm việc đa nhiệm trong thời gian dài.",
    specs: {
      CPU: "AMD Ryzen 9 9900X",
      GPU: "NVIDIA GeForce RTX 4070 Ti SUPER 16GB",
      RAM: "64GB DDR5",
      SSD: "2TB NVMe",
      Cooling: "AIO 360mm",
    },
    featured: true,
    tags: ["creator", "desktop", "workstation"],
  },
  {
    id: "p15",
    name: "Samsung Odyssey G6 32",
    slug: "samsung-odyssey-g6-32",
    categoryId: "cat-monitor",
    brand: "Samsung",
    price: 10990000,
    originalPrice: 12990000,
    rating: 4.7,
    reviewCount: 71,
    stock: 10,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Màn hình cong 32 inch cho game nhập vai và giải trí.",
    description:
      "Tỷ lệ tương phản cao, màu sắc rực rỡ và màn hình cong giúp tăng độ đắm chìm khi chơi game.",
    specs: {
      Resolution: "2560x1440",
      Panel: "VA cong 1000R",
      RefreshRate: "240Hz",
      HDR: "VESA DisplayHDR 600",
      Size: "32 inch",
    },
    onSale: true,
    tags: ["monitor", "curved", "gaming"],
  },
  {
    id: "p16",
    name: "Anker Prime Charging Station 8-in-1",
    slug: "anker-prime-charging-station-8-in-1",
    categoryId: "cat-accessory",
    brand: "Anker",
    price: 3990000,
    originalPrice: 4590000,
    rating: 4.6,
    reviewCount: 55,
    stock: 25,
    image: "https://images.unsplash.com/photo-1585338447937-7082f8fc763d?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1585338447937-7082f8fc763d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Trạm sạc công suất cao cho laptop, điện thoại và phụ kiện bàn làm việc.",
    description:
      "Phụ kiện phù hợp với người dùng có nhiều thiết bị và muốn gom gọn khu vực làm việc vào một nguồn sạc trung tâm. Thiết kế đặt bàn, nhiều cổng và công suất lớn giúp việc sạc laptop, điện thoại và phụ kiện trở nên gọn gàng hơn.",
    specs: {
      Power: "240W",
      Ports: "4 x USB-C, 2 x USB-A, 2 ổ AC",
      Charging: "Sạc nhanh đa thiết bị",
      Material: "Aluminum",
      UseCase: "Bàn làm việc / phòng họp",
    },
    onSale: true,
    tags: ["dock", "charger", "workspace"],
  },
  {
    id: "p17",
    name: "MSI Creator Z17 HX AI",
    slug: "msi-creator-z17-hx-ai",
    categoryId: "cat-laptop",
    brand: "MSI",
    price: 58990000,
    originalPrice: 61990000,
    rating: 4.8,
    reviewCount: 42,
    stock: 5,
    image: "https://images.unsplash.com/photo-1504707748692-419802cf939d?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1504707748692-419802cf939d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Laptop màn lớn cho designer, editor và kỹ sư cần hiệu năng cao.",
    description:
      "MSI Creator Z17 HX AI hướng tới người làm sáng tạo nội dung chuyên nghiệp cần màn hình chuẩn màu, CPU đa nhân mạnh và GPU rời đủ lực cho Premiere, After Effects hay Blender. Khung máy chắc chắn, bàn rê rộng và hệ thống tản nhiệt lớn giúp thiết bị giữ hiệu năng ổn định khi render dài.",
    specs: {
      CPU: "Intel Core Ultra 9 285H",
      GPU: "NVIDIA RTX 5070 Laptop",
      RAM: "32GB DDR5",
      SSD: "2TB NVMe",
      Display: "17 inch QHD+ 165Hz 100% DCI-P3",
    },
    featured: true,
    onSale: true,
    isNew: true,
    tags: ["creator", "design", "high-performance"],
  },
  {
    id: "p18",
    name: "HP EliteBook Ultra G1q",
    slug: "hp-elitebook-ultra-g1q",
    categoryId: "cat-laptop",
    brand: "HP",
    price: 35990000,
    rating: 4.6,
    reviewCount: 31,
    stock: 9,
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Ultrabook doanh nhân mỏng nhẹ, pin dài và tối ưu họp trực tuyến.",
    description:
      "EliteBook Ultra G1q phù hợp đội ngũ quản lý, sale và người thường xuyên di chuyển với nhu cầu làm việc cloud, họp online, xử lý tài liệu và thuyết trình. Thiết bị tập trung vào độ bền, webcam tốt, AI hỗ trợ họp và thời lượng pin dài để dùng xuyên ngày.",
    specs: {
      CPU: "Snapdragon X Elite",
      RAM: "16GB LPDDR5X",
      SSD: "1TB NVMe",
      Display: "14 inch 2.2K touch",
      Weight: "1.34kg",
    },
    featured: true,
    tags: ["business", "ultrabook", "meeting"],
  },
  {
    id: "p19",
    name: "ViewSonic ColorPro VP2776",
    slug: "viewsonic-colorpro-vp2776",
    categoryId: "cat-monitor",
    brand: "ViewSonic",
    price: 13990000,
    originalPrice: 14990000,
    rating: 4.7,
    reviewCount: 37,
    stock: 11,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Màn hình chuẩn màu cho designer, chỉnh ảnh và dựng video.",
    description:
      "ColorPro VP2776 tập trung vào độ chính xác màu sắc ngay từ khi mở hộp, phù hợp với studio nhỏ, bộ phận marketing và freelancer làm ảnh, UI hoặc video. Thiết kế tối giản, chân đế linh hoạt và cổng kết nối đầy đủ giúp dễ tích hợp vào bàn làm việc hiện đại.",
    specs: {
      Resolution: "2560x1440",
      Panel: "IPS 100% sRGB / 98% DCI-P3",
      Calibration: "Factory calibrated Delta E < 2",
      Ports: "USB-C, HDMI, DisplayPort",
      Size: "27 inch",
    },
    onSale: true,
    tags: ["monitor", "color-accurate", "design"],
  },
  {
    id: "p20",
    name: "Belkin BoostCharge Pro 3-in-1",
    slug: "belkin-boostcharge-pro-3-in-1",
    categoryId: "cat-accessory",
    brand: "Belkin",
    price: 3490000,
    originalPrice: 3890000,
    rating: 4.7,
    reviewCount: 66,
    stock: 28,
    image: "https://images.unsplash.com/photo-1585338447937-7082f8fc763d?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1585338447937-7082f8fc763d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Đế sạc không dây gọn gàng cho iPhone, Apple Watch và AirPods.",
    description:
      "Phụ kiện dành cho người dùng hệ sinh thái Apple muốn tối giản dây cáp và giữ bàn làm việc gọn mắt. Thiết kế dựng đứng tiện theo dõi thông báo khi sạc, phù hợp đặt tại bàn làm việc hoặc đầu giường nhờ hoàn thiện đẹp và khả năng sạc ổn định.",
    specs: {
      Charging: "MagSafe 15W",
      Compatibility: "iPhone, Apple Watch, AirPods",
      Material: "Soft-touch aluminum frame",
      Cable: "USB-C braided cable",
      UseCase: "Desk setup / bedside",
    },
    onSale: true,
    tags: ["charger", "apple", "wireless"],
  },
  {
    id: "p21",
    name: "Acer Swift Go 14 OLED",
    slug: "acer-swift-go-14-oled",
    categoryId: "cat-laptop",
    brand: "Acer",
    price: 24990000,
    originalPrice: 26990000,
    rating: 4.6,
    reviewCount: 52,
    stock: 17,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Laptop mỏng nhẹ màn OLED cho học tập, làm việc và giải trí.",
    description:
      "Acer Swift Go 14 OLED phù hợp sinh viên và dân văn phòng cần một mẫu laptop gọn, pin ổn và màn hình đẹp để làm việc mỗi ngày. Máy cân bằng tốt giữa hiệu năng, độ cơ động và trải nghiệm hiển thị cho các tác vụ đa nhiệm phổ thông.",
    specs: {
      CPU: "Intel Core Ultra 7 155H",
      RAM: "16GB LPDDR5X",
      SSD: "1TB NVMe",
      Display: "14 inch OLED 2.8K 90Hz",
      Weight: "1.3kg",
    },
    featured: true,
    onSale: true,
    tags: ["oled", "office", "student"],
  },
  {
    id: "p22",
    name: "ASUS TUF Gaming A16",
    slug: "asus-tuf-gaming-a16",
    categoryId: "cat-laptop",
    brand: "ASUS",
    price: 31990000,
    originalPrice: 33990000,
    rating: 4.7,
    reviewCount: 48,
    stock: 11,
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1504707748692-419802cf939d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Laptop gaming 16 inch bền bỉ cho học tập và chơi game dài giờ.",
    description:
      "ASUS TUF Gaming A16 hướng tới người dùng cần laptop gaming hiệu năng tốt, bàn phím thoải mái và hệ thống tản nhiệt ổn định trong tầm giá. Thiết bị phù hợp cả chơi game phổ biến, stream cơ bản và xử lý đồ họa bán chuyên.",
    specs: {
      CPU: "AMD Ryzen 9 8940HX",
      GPU: "NVIDIA RTX 4060 Laptop",
      RAM: "16GB DDR5",
      SSD: "1TB NVMe",
      Display: "16 inch WQXGA 165Hz",
    },
    featured: true,
    onSale: true,
    tags: ["gaming", "performance", "16-inch"],
  },
  {
    id: "p23",
    name: "PC Mini ITX Compact Pro",
    slug: "pc-mini-itx-compact-pro",
    categoryId: "cat-pc",
    brand: "GearHub Build",
    price: 28990000,
    originalPrice: 30990000,
    rating: 4.6,
    reviewCount: 29,
    stock: 7,
    image: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "PC nhỏ gọn cho bàn làm việc tối giản nhưng vẫn mạnh mẽ.",
    description:
      "PC Mini ITX Compact Pro dành cho người dùng cần một bộ máy tiết kiệm diện tích mà vẫn đủ mạnh cho công việc sáng tạo, chơi game eSports và sử dụng hằng ngày. Cấu hình được tối ưu để vận hành ổn định, dễ bảo trì và phù hợp các setup gọn gàng hiện đại.",
    specs: {
      CPU: "AMD Ryzen 7 9700X",
      GPU: "RTX 4060 8GB",
      RAM: "32GB DDR5",
      SSD: "1TB NVMe",
      Case: "Mini ITX airflow",
    },
    onSale: true,
    tags: ["desktop", "compact", "itx"],
  },
  {
    id: "p24",
    name: "PC Office Pro Dual Monitor",
    slug: "pc-office-pro-dual-monitor",
    categoryId: "cat-pc",
    brand: "GearHub Build",
    price: 17990000,
    rating: 4.5,
    reviewCount: 41,
    stock: 12,
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "PC văn phòng đa nhiệm ổn định cho doanh nghiệp và làm việc tại nhà.",
    description:
      "PC Office Pro Dual Monitor phù hợp bộ phận kế toán, chăm sóc khách hàng và người làm việc với nhiều cửa sổ cùng lúc. Hệ thống ưu tiên độ ổn định, khả năng xuất hai màn hình và mức tiêu thụ điện hợp lý cho môi trường làm việc dài giờ.",
    specs: {
      CPU: "Intel Core i5-14500",
      GPU: "Intel UHD Graphics",
      RAM: "16GB DDR5",
      SSD: "1TB NVMe",
      Connectivity: "Dual HDMI + DisplayPort",
    },
    tags: ["office", "business", "multitasking"],
  },
  {
    id: "p25",
    name: "Google Pixel 9 Pro XL",
    slug: "google-pixel-9-pro-xl",
    categoryId: "cat-phone",
    brand: "Google",
    price: 25990000,
    originalPrice: 27990000,
    rating: 4.7,
    reviewCount: 57,
    stock: 16,
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Điện thoại Android cao cấp với camera mạnh và trải nghiệm Google thuần.",
    description:
      "Pixel 9 Pro XL phù hợp người dùng thích chụp ảnh nhanh, giao diện Android sạch và cập nhật phần mềm sớm. Máy nổi bật với camera điện toán mạnh, nhiều tính năng AI hữu ích và trải nghiệm đồng bộ tốt trong hệ sinh thái Google.",
    specs: {
      Chip: "Google Tensor G4",
      Display: "6.8 inch LTPO OLED 120Hz",
      Camera: "50MP Wide + 48MP Ultra Wide + 48MP Tele 5x",
      Storage: "256GB",
      Battery: "Hơn 24 giờ sử dụng",
    },
    featured: true,
    onSale: true,
    tags: ["android", "camera", "ai"],
  },
  {
    id: "p26",
    name: "OPPO Find X8 Pro",
    slug: "oppo-find-x8-pro",
    categoryId: "cat-phone",
    brand: "OPPO",
    price: 22990000,
    originalPrice: 24990000,
    rating: 4.6,
    reviewCount: 63,
    stock: 21,
    image: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Flagship mỏng đẹp với camera chân dung và sạc nhanh ấn tượng.",
    description:
      "OPPO Find X8 Pro hướng tới người dùng thích thiết kế sang, màn hình đẹp và camera linh hoạt cho cả chụp chân dung lẫn quay video ngắn. Máy cũng phù hợp nhu cầu sử dụng cường độ cao nhờ pin lớn và khả năng sạc nhanh tiện lợi.",
    specs: {
      Chip: "MediaTek Dimensity 9400",
      Display: "6.82 inch AMOLED 120Hz",
      Camera: "50MP Hasselblad quad camera",
      Storage: "512GB",
      Battery: "5.800mAh",
    },
    onSale: true,
    isNew: true,
    tags: ["android", "portrait", "fast-charge"],
  },
  {
    id: "p27",
    name: "Dell UltraSharp U2724DE",
    slug: "dell-ultrasharp-u2724de",
    categoryId: "cat-monitor",
    brand: "Dell",
    price: 11990000,
    originalPrice: 12990000,
    rating: 4.8,
    reviewCount: 46,
    stock: 14,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Màn hình 27 inch USB-C cho dân văn phòng, lập trình và thiết kế nhẹ.",
    description:
      "Dell UltraSharp U2724DE phù hợp môi trường làm việc chuyên nghiệp cần màu sắc ổn định, cổng kết nối hiện đại và khả năng kết nối laptop qua một dây. Chân đế linh hoạt, viền mỏng và hub USB tích hợp giúp tối ưu bàn làm việc gọn gàng.",
    specs: {
      Resolution: "2560x1440",
      Panel: "IPS Black",
      RefreshRate: "120Hz",
      Ports: "USB-C hub, HDMI, DisplayPort, LAN",
      Size: "27 inch",
    },
    featured: true,
    tags: ["monitor", "office", "usb-c"],
  },
  {
    id: "p28",
    name: "Gigabyte M32U",
    slug: "gigabyte-m32u",
    categoryId: "cat-monitor",
    brand: "Gigabyte",
    price: 15990000,
    originalPrice: 17490000,
    rating: 4.7,
    reviewCount: 54,
    stock: 8,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Màn hình 4K 144Hz cho game console, PC cao cấp và sáng tạo nội dung.",
    description:
      "Gigabyte M32U mang lại không gian hiển thị lớn, độ phân giải 4K sắc nét và tần số quét cao cho người dùng cần một màn hình đa dụng. Sản phẩm phù hợp cả chơi game console thế hệ mới, làm video và xử lý ảnh nhờ độ chi tiết tốt và hệ cổng đầy đủ.",
    specs: {
      Resolution: "3840x2160",
      Panel: "SuperSpeed IPS",
      RefreshRate: "144Hz",
      Ports: "HDMI 2.1, DisplayPort, USB hub",
      Size: "31.5 inch",
    },
    onSale: true,
    tags: ["4k", "gaming", "console"],
  },
  {
    id: "p29",
    name: "Razer BlackWidow V4 Pro",
    slug: "razer-blackwidow-v4-pro",
    categoryId: "cat-accessory",
    brand: "Razer",
    price: 5990000,
    originalPrice: 6490000,
    rating: 4.7,
    reviewCount: 39,
    stock: 18,
    image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541140532154-b024d705b90a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Bàn phím cơ full-size cao cấp cho game thủ và streamer.",
    description:
      "Razer BlackWidow V4 Pro phù hợp người dùng cần một bàn phím cơ đầy đủ chức năng, hành trình gõ rõ ràng và hệ thống điều khiển media tiện lợi. Thiết bị phát huy tốt trong setup chơi game, stream hoặc làm việc cần macro và phím tắt chuyên sâu.",
    specs: {
      Layout: "Full-size",
      Switch: "Razer Green Mechanical",
      Connectivity: "USB-C detachable",
      Lighting: "Per-key RGB",
      Extras: "Command dial + macro keys",
    },
    featured: true,
    onSale: true,
    tags: ["keyboard", "gaming", "rgb"],
  },
  {
    id: "p30",
    name: "UGREEN Nexode 200W GaN Charger",
    slug: "ugreen-nexode-200w-gan-charger",
    categoryId: "cat-accessory",
    brand: "UGREEN",
    price: 2690000,
    originalPrice: 2990000,
    rating: 4.6,
    reviewCount: 58,
    stock: 34,
    image: "https://images.unsplash.com/photo-1585338447937-7082f8fc763d?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1585338447937-7082f8fc763d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    ],
    shortDescription: "Củ sạc GaN công suất lớn cho laptop, điện thoại và tablet.",
    description:
      "UGREEN Nexode 200W GaN Charger là lựa chọn thực dụng cho người dùng mang nhiều thiết bị cùng lúc và muốn giảm số lượng củ sạc phải mang theo. Công suất lớn, nhiều cổng USB-C và thiết kế gọn giúp sản phẩm phù hợp cho bàn làm việc lẫn các chuyến công tác.",
    specs: {
      Power: "200W GaN",
      Ports: "4 x USB-C, 2 x USB-A",
      Compatibility: "Laptop, phone, tablet, accessories",
      Protection: "Overheat and surge protection",
      UseCase: "Travel / desk setup",
    },
    onSale: true,
    tags: ["charger", "gan", "multi-device"],
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    productId: "p1",
    userId: "u2",
    author: "Nguyen Minh",
    rating: 5,
    comment: "Máy mượt, màn đẹp và pin tốt hơn mình nghĩ.",
    createdAt: "2026-03-01",
    status: "approved",
  },
  {
    id: "r2",
    productId: "p1",
    userId: "u3",
    author: "Tran Bao",
    rating: 4,
    comment: "Tản ổn, chơi game ngon nhưng giá hơi cao.",
    createdAt: "2026-03-10",
    status: "approved",
  },
  {
    id: "r3",
    productId: "p4",
    userId: "u2",
    author: "Le Anh",
    rating: 5,
    comment: "Camera và quay video rất tốt, hệ sinh thái dùng tiện.",
    createdAt: "2026-03-14",
    status: "approved",
  },
  {
    id: "r4",
    productId: "p9",
    userId: "u3",
    author: "Hoang Linh",
    rating: 5,
    comment: "Máy nhẹ, pin khỏe và gần như không nóng trong các tác vụ văn phòng hằng ngày.",
    createdAt: "2026-03-16",
    status: "approved",
  },
  {
    id: "r5",
    productId: "p14",
    userId: "u2",
    author: "Pham Khoa",
    rating: 5,
    comment: "Render Premiere ổn định, mở nhiều project nặng vẫn mượt và tiếng ồn dễ chịu.",
    createdAt: "2026-03-18",
    status: "approved",
  },
  {
    id: "r6",
    productId: "p17",
    userId: "u2",
    author: "Bui Nhat",
    rating: 4,
    comment: "Máy chạy ổn định khi render dài, màn hình chuẩn màu và bàn phím gõ khá thoải mái cho công việc sáng tạo.",
    createdAt: "2026-03-20",
    status: "approved",
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "b1",
    title: "5 tiêu chí chọn laptop cho sinh viên IT năm 2026",
    slug: "chon-laptop-cho-sinh-vien-it-2026",
    excerpt:
      "CPU đủ mạnh, RAM tối thiểu 16GB, màn hình dễ nhìn và trọng lượng hợp lý là nền tảng để sinh viên IT học tốt mà không lãng phí ngân sách.",
    cover: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=1200&q=80",
    category: "Tư vấn mua hàng",
    publishedAt: "2026-03-15",
    readTime: "7 phút",
    content: [
      "Sinh viên IT thường phải mở cùng lúc IDE, trình duyệt nhiều tab, Figma, Docker hoặc máy ảo. Vì vậy, bộ xử lý dòng mới và 16GB RAM gần như là mức khởi điểm hợp lý nếu bạn muốn máy dùng ổn định ít nhất 3 đến 4 năm đại học.",
      "SSD 512GB cũng quan trọng không kém. Nhiều bạn chỉ nhìn CPU rồi tiết kiệm ở phần lưu trữ, nhưng sau một vài kỳ học với source code, tài liệu, dataset và phần mềm chuyên ngành, 256GB sẽ nhanh chóng chật chội.",
      "Trọng lượng và pin là yếu tố dễ bị xem nhẹ khi mua máy lần đầu. Nếu bạn đi học mỗi ngày, một chiếc máy khoảng 1.3 đến 1.6kg sẽ dễ chịu hơn rất nhiều so với laptop gaming gần 2.5kg, đặc biệt khi còn phải mang thêm sạc và phụ kiện.",
      "Với nhóm học AI, đồ họa hoặc game, laptop gaming vẫn có giá trị nhờ GPU rời. Tuy nhiên, hãy cân nhắc thật kỹ vì đổi lại bạn sẽ chịu mức giá cao hơn, pin ngắn hơn và tiếng quạt lớn hơn trong môi trường lớp học hoặc thư viện.",
      "Một lựa chọn khôn ngoan là mua đúng theo nhu cầu hiện tại và chừa ngân sách cho màn hình rời, chuột hoặc SSD nâng cấp sau này. Tổng trải nghiệm học tập thường đến từ cả hệ sinh thái sử dụng, không chỉ từ cấu hình trên giấy.",
    ],
  },
  {
    id: "b2",
    title: "So sánh PC gaming và laptop gaming: nên mua gì?",
    slug: "so-sanh-pc-gaming-va-laptop-gaming",
    excerpt:
      "PC cho hiệu năng và khả năng nâng cấp tốt hơn trên cùng ngân sách, còn laptop gaming phù hợp người cần một thiết bị cơ động, gọn không gian.",
    cover: "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80",
    category: "Review",
    publishedAt: "2026-03-12",
    readTime: "6 phút",
    content: [
      "Nếu xét riêng hiệu năng trên mỗi đồng chi phí, PC gaming gần như luôn thắng. Bạn có thể đầu tư nhiều hơn cho card đồ họa, tản nhiệt tốt hơn và dễ đạt mức FPS cao ở độ phân giải 2K hoặc 4K mà không phải trả thêm cho màn hình, bàn phím hay pin tích hợp.",
      "Điểm mạnh lớn nhất của laptop gaming là sự tiện lợi. Người dùng ở ký túc xá, căn hộ nhỏ hoặc thường xuyên di chuyển giữa nhà và công ty sẽ đánh giá cao việc chỉ cần một thiết bị là có thể vừa làm việc vừa giải trí.",
      "Khả năng nâng cấp cũng là khác biệt quan trọng. PC cho phép thay GPU, thêm SSD, đổi nguồn và tối ưu từng thành phần theo ngân sách từng giai đoạn, trong khi laptop thường chỉ nâng được RAM và SSD.",
      "Ngược lại, laptop lại ít rườm rà hơn khi mới bắt đầu. Bạn không phải mua thêm màn hình, webcam, bàn phím hay UPS ngay từ đầu nếu ngân sách còn hạn chế hoặc chưa muốn đầu tư cả bộ máy bàn.",
      "Cách chọn phù hợp nhất là nhìn vào nơi bạn sử dụng thiết bị nhiều nhất. Nếu bạn ngồi cố định và ưu tiên sức mạnh lâu dài, hãy chọn PC. Nếu bạn cần linh hoạt và tối giản setup, laptop gaming sẽ đáng tiền hơn.",
    ],
  },
  {
    id: "b3",
    title: "Thiết lập góc làm việc tại nhà gọn đẹp mà vẫn tối ưu hiệu suất",
    slug: "thiet-lap-goc-lam-viec-tai-nha-toi-uu-hieu-suat",
    excerpt:
      "Một góc làm việc hiệu quả không cần quá đắt, nhưng cần ưu tiên đúng thứ tự: màn hình, ghế ngồi, ánh sáng, dock kết nối và cách quản lý dây cáp.",
    cover: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
    category: "Kinh nghiệm sử dụng",
    publishedAt: "2026-03-20",
    readTime: "5 phút",
    content: [
      "Khi thiết lập bàn làm việc tại nhà, nhiều người thường đầu tư vào phụ kiện đẹp trước khi giải quyết các vấn đề ảnh hưởng trực tiếp tới năng suất. Trên thực tế, một màn hình đủ lớn và một chiếc ghế ngồi đúng tư thế thường tạo khác biệt rõ rệt hơn so với bàn phím đắt tiền.",
      "Nếu dùng laptop là thiết bị chính, dock mở rộng cổng là món phụ kiện rất đáng giá. Nó giúp bạn kết nối màn hình, mạng LAN, ổ cứng ngoài và sạc chỉ qua một dây, giảm đáng kể thời gian cắm rút mỗi ngày.",
      "Ánh sáng cũng cần được bố trí có chủ đích. Ánh sáng tự nhiên lệch bên hông, kết hợp đèn bàn nhiệt màu trung tính, sẽ giúp mắt đỡ mỏi hơn khi phải nhìn màn hình liên tục trong nhiều giờ.",
      "Sau cùng, đừng đánh giá thấp việc quản lý dây cáp. Dùng kẹp dây, đế sạc đa thiết bị và bố trí nguồn điện hợp lý sẽ làm góc làm việc gọn hơn, dễ vệ sinh hơn và tạo cảm giác muốn ngồi vào làm việc mỗi ngày.",
    ],
  },
  {
    id: "b4",
    title: "OLED hay IPS: nên chọn màn hình nào cho chơi game và làm việc?",
    slug: "oled-hay-ips-nen-chon-man-hinh-nao",
    excerpt:
      "OLED cho độ tương phản và tốc độ phản hồi ấn tượng, còn IPS vẫn là lựa chọn an toàn về giá, độ sáng và độ bền cho nhiều nhu cầu hỗn hợp.",
    cover: "https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=1200&q=80",
    category: "Tư vấn mua hàng",
    publishedAt: "2026-03-18",
    readTime: "6 phút",
    content: [
      "Màn hình OLED hấp dẫn ngay từ lần đầu nhìn nhờ màu đen sâu, độ tương phản rất cao và thời gian phản hồi gần như tức thì. Với game tốc độ cao hoặc phim ảnh, trải nghiệm mà OLED mang lại thực sự khác biệt.",
      "Tuy nhiên, IPS vẫn là lựa chọn cân bằng hơn cho số đông. Mức giá dễ tiếp cận, độ sáng tốt và ít lo ngại lưu ảnh khiến IPS phù hợp với người dùng làm việc văn phòng, học tập và chơi game ở mức vừa phải.",
      "Nếu bạn làm thiết kế hoặc chỉnh ảnh, hãy nhìn thêm vào độ phủ màu và khả năng cân màu xuất xưởng thay vì chỉ chọn theo công nghệ tấm nền. Một màn IPS chuẩn màu tốt vẫn hữu ích hơn một màn OLED thiên giải trí.",
      "Với game thủ eSports, yếu tố quan trọng nhất là tần số quét, độ trễ và độ rõ chuyển động. Một màn IPS 240Hz chất lượng cao đôi khi hợp lý hơn OLED nếu bạn ưu tiên chi phí và thi đấu lâu dài.",
      "Cách chọn đúng là bắt đầu từ nhu cầu chính của bạn. OLED dành cho trải nghiệm hình ảnh cao cấp và giải trí đắm chìm; IPS phù hợp khi bạn cần màn hình đa dụng, giá hợp lý và vận hành ổn định lâu dài.",
    ],
  },
  {
    id: "b5",
    title: "Chọn điện thoại cho người làm nội dung: cần quan tâm gì ngoài camera?",
    slug: "chon-dien-thoai-cho-nguoi-lam-noi-dung",
    excerpt:
      "Người làm nội dung không chỉ cần camera đẹp mà còn phải quan tâm tới bộ nhớ, thu âm, pin, màn hình và sự ổn định khi quay chụp liên tục.",
    cover: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
    category: "Review",
    publishedAt: "2026-03-10",
    readTime: "5 phút",
    content: [
      "Camera luôn là yếu tố được nhắc đến đầu tiên, nhưng với người quay reels, vlog ngắn hay review sản phẩm, dung lượng bộ nhớ và khả năng duy trì hiệu năng khi quay lâu cũng quan trọng không kém. Một chiếc máy quay đẹp nhưng nóng nhanh sẽ làm gián đoạn quy trình sáng tạo.",
      "Màn hình sáng và hiển thị màu chính xác giúp bạn kiểm tra khung hình ngay tại chỗ, đặc biệt khi quay ngoài trời hoặc cần chỉnh tone màu cơ bản trước khi đăng. Đây là điểm khác biệt rõ giữa các mẫu flagship và nhóm cận cao cấp.",
      "Âm thanh cũng không nên bị bỏ qua. Nhiều người quay nói chuyện trực tiếp bằng micro tích hợp, nên thuật toán lọc ồn, khả năng bắt giọng và cổng kết nối phụ kiện sẽ ảnh hưởng lớn tới chất lượng nội dung cuối cùng.",
      "Cuối cùng là hệ sinh thái. Nếu bạn dựng video trên MacBook, dùng iPhone có thể thuận tiện hơn ở bước đồng bộ file. Ngược lại, người dùng Windows hoặc thích tùy biến mạnh có thể sẽ làm việc thoải mái hơn với flagship Android.",
    ],
  },
  {
    id: "b6",
    title: "Checklist trước khi mua PC lắp sẵn để tránh tốn tiền nâng cấp sớm",
    slug: "checklist-truoc-khi-mua-pc-lap-san",
    excerpt:
      "Đừng chỉ nhìn CPU và GPU. Mainboard, nguồn, tản nhiệt, luồng gió và chính sách bảo hành mới là những yếu tố quyết định tuổi thọ của bộ PC lắp sẵn.",
    cover: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
    category: "Tư vấn mua hàng",
    publishedAt: "2026-03-08",
    readTime: "7 phút",
    content: [
      "PC lắp sẵn hấp dẫn vì bạn không phải tự chọn linh kiện từng món, nhưng cũng dễ mắc bẫy cấu hình nếu chỉ nhìn vào CPU và card đồ họa. Nhiều bộ máy dùng nguồn công suất thấp, mainboard cắt giảm tính năng hoặc tản nhiệt không đủ cho tải nặng.",
      "Nguồn điện nên được xem như nền móng của hệ thống. Một bộ nguồn đạt chuẩn 80 Plus từ thương hiệu uy tín sẽ giúp máy vận hành ổn định, dễ nâng cấp GPU sau này và giảm rủi ro khi chạy tải nặng kéo dài.",
      "Tản nhiệt và luồng gió trong case cũng rất đáng kiểm tra. Cùng một cấu hình nhưng máy có bố trí quạt hợp lý và mặt lưới thoáng sẽ êm hơn, mát hơn và ít bị tụt hiệu năng hơn sau vài giờ chơi game hoặc render.",
      "Bạn cũng nên hỏi rõ về số khe RAM còn trống, số khe SSD M.2 và kích thước case. Đây là những chi tiết nhỏ nhưng quyết định việc nâng cấp sau này có dễ hay không và có phải thay thêm linh kiện phụ trợ hay không.",
      "Một bộ PC lắp sẵn đáng mua là bộ máy cân bằng giữa hiệu năng hiện tại và khả năng mở rộng tương lai. Chọn đúng từ đầu sẽ giúp bạn tiết kiệm hơn nhiều so với việc phải thay nguồn, thay tản hoặc đổi case chỉ sau vài tháng sử dụng.",
    ],
  },
];

export const orders: Order[] = [
  {
    id: "OD001",
    userId: "u2",
    customerName: "Pham Tuan",
    customerEmail: "hai@gmail.com",
    phone: "0909000111",
    address: "Q.1, TP.HCM",
    paymentMethod: "cod",
    status: "pending",
    total: 42990000,
    createdAt: "2026-03-19",
    note: "Giao giờ hành chính",
    items: [
      {
        id: "p1",
        name: "ASUS ROG Zephyrus G14",
        slug: "asus-rog-zephyrus-g14",
        image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
        price: 42990000,
        quantity: 1,
      },
    ],
  },
  {
    id: "OD002",
    userId: "u3",
    customerName: "Le Thu",
    customerEmail: "linh@gmail.com",
    phone: "0988111222",
    address: "Ha Noi",
    paymentMethod: "online",
    status: "delivered",
    total: 67880000,
    createdAt: "2026-03-17",
    items: [
      {
        id: "p4",
        name: "iPhone 16 Pro Max",
        slug: "iphone-16-pro-max",
        image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
        price: 33990000,
        quantity: 2,
      },
    ],
  },
];

export const users: User[] = [
  {
    id: "u1",
    name: "Trần Đông Quân",
    email: "trandongquan9@gmail.com",
    phone: "0933858157",
    address: "127 Nguyen Hue, Quan 1, TP.HCM",
    role: "admin",
    status: "active",
    createdAt: "2026-01-01",
  },
  {
    id: "u2",
    name: "Nguyen Hai",
    email: "hai@gmail.com",
    phone: "0909000111",
    address: "45 Vo Van Tan, Quan 3, TP.HCM",
    role: "customer",
    status: "active",
    createdAt: "2026-02-12",
  },
  {
    id: "u3",
    name: "Tran Linh",
    email: "linh@gmail.com",
    phone: "0988111222",
    address: "22 Cau Giay, Ha Noi",
    role: "customer",
    status: "locked",
    createdAt: "2026-03-03",
  },
];
